// Canonical lists for presentations and modalities
// Used in ManageAvailability dropdowns and TaxonomyTab

export const CANONICAL_PRESENTATIONS: string[] = [
  // Anxiety & Stress
  "Anxiety",
  "Generalized Anxiety Disorder (GAD)",
  "Health Anxiety",
  "Health Anxiety/ Medical Trauma",
  "Social anxiety disorder / Social Phobia",
  "Separation anxiety disorder",
  "Panic Disorder & Panic Attacks",
  "Agoraphobia",
  "Claustrophobia",
  "Phobias",
  "Perfectionism",
  "Perfectionism or Imposter Syndrome",
  "Imposter Syndrome",
  "Fear of Failure",
  "Stress",
  "Work Stress",
  "Workplace stress",
  "Occupational stress or burnout",
  "Burnout",
  "Work-life balance challenges",
  "Academic pressure / performance stress",
  "Compassion fatigue / vicarious trauma",

  // Mood & Depression
  "Depression",
  "Clinical Depression (Major Depressive Disorder)",
  "Major Depressive Disorder",
  "Persistent Depressive Disorder (Dysthymia)",
  "Bipolar Disorder",
  "Seasonal Affective Disorder",
  "Disruptive Mood Dysregulation Disorder",
  "Emotion Dysregulation / Impulsivity",
  "Emotional suppression / anger issues",
  "Intermittent Explosive Disorder (Uncontrolled Anger)",

  // Trauma
  "Trauma",
  "Complex Trauma",
  "Post Traumatic Stress Disorder (PTSD)",
  "Intergenerational Trauma",
  "Childhood Abuse and Neglect",
  "Sexual Abuse / Assault",
  "Domestic or Family Violence",
  "Interpersonal trauma or betrayal",
  "Pregnancy loss or birth trauma",

  // Eating & Body
  "Eating Disorders",
  "Eating Disorders (Not Current)",
  "Eating Disorders (Recent Diagnosis or Suspected)",
  "Anorexia Nervosa",
  "Anorexia Nervosa ( not current)",
  "Anorexia Nervosa (Recent Diagnosis or suspected)",
  "Bulimia Nervosa",
  "Bulimia Nervosa ( NOT CURRENT)",
  "Bulimia Nervosa (Recent Diagnosis or suspected)",
  "Binge-Eating Disorder",
  "Binge-Eating Disorder (Not Current)",
  "Binge-Eating Disorder (Recent Diagnosis or suspected)",
  "Body Dysmorphic Disorder",
  "Body issues",
  "Emotional Eating",

  // Addictions & Substance
  "Addictions",
  "Substance Misuse",
  "Alcohol Dependence",
  "Alcohol Dependence (Not Current)",
  "Alcohol Dependence (Recent Diagnosis or suspected)",
  "Cannabis Dependence",
  "Cannabis Dependence ( Not Current)",
  "Cannabis Dependence (Recent diagnoisis or Suspected)",
  "Drug Dependence (Not Current)",
  "Drug Dependence (Recent Diagnosis or Suspected)",
  "Addictions - Gambling",
  "Addictions - Gaming",
  "Compulsive Pornography use",
  "Hypersexuality (Sex Addiction)",
  "Compulsive Shopping",

  // Relationships & Family
  "Couples and Marriage Difficulties",
  "Relationship Concerns",
  "Relationship breakdown",
  "Separation / divorce adjustment",
  "Communication and boundary issues",
  "Codependency or people-pleasing",
  "Intimacy and trust difficulties",
  "Sex and intimacy",
  "Non-Monogomy/ Polyamory",
  "Family conflict or parental separation adjustment",
  "Family Conflict/ belnded family stress",
  "Erectile Dysfunction",
  "Sexual problems",

  // Self & Identity
  "Self esteem",
  "Low self esteem",
  "Self-Esteem & Confidence",
  "Confidence",
  "Vulnerability",
  "Identity exploration (gender / sexual orientation / cultural / spiritual)",
  "LGBTQIA+ affirmative therapy",
  "LGBTIQA+",
  "Gender Dysphoria (form. Gender Identity Disorder)",
  "Sexuality and Gender",
  "Queer",
  "Refugees / migrants / asylum seekers",
  "Culturally and linguistically diverse clients",

  // Self-Harm & Crisis
  "Self-Harm or Suicidal Ideation (Non-Crisis Support)",
  "Self-Harm (Cutting)",
  "Self-harm or risky behaviours",
  "Suicidal Ideation",

  // Neurodevelopmental & Cognitive
  "ADD and ADHD",
  "ADHD",
  "Autism Spectrum Disorders (ASD)",
  "Asperger Syndrome",
  "Learning Difficulties",
  "Executive functioning challenges",
  "Sensory processing differences",
  "Cognitive decline / memory concerns",
  "Intellectual Development Disorder (form. Mental Retardation)",

  // Personality Disorders
  "Borderline Personality Disorder (BPD)",
  "Borderline Personality Disorder",
  "Narcissistic Personality Disorder",
  "Narcissistic traits or trauma recovery from narcissistic abuse",
  "Avoidant Personality Disorder",
  "Antisocial Personality Disorder",
  "Personality Disorder",
  "DDNOS",
  "Dissociative Identity Disorder",
  "Dissociative Identity Disorder (Multiple Personality Disorder)",
  "Depersonalization Disorder",

  // OCD & Intrusive Thoughts
  "Obsessive-Compulsive Disorder (OCD)",
  "Perfectionistic / obsessive personality patterns",

  // Perinatal & Parenting
  "Pregnancy and Postnatal Depression",
  "Pregnancy and Postnatal Depression Anxiety",
  "Perinatal Anxiety and Depression",
  "Fertility / IVF stress",
  "Balancing multiple roles (career / parenting / caregiving)",
  "Relationship or parenting stress",

  // Life Transitions & Existential
  "Life Transitions",
  "Career transition",
  "Career dissatisfaction or change adjustment",
  "Life transitions (career change / relocation / retirement / ageing)",
  "Adjusting to fatherhood or retirement",
  "Menopause adjustment",
  "Midlife crisis or \"stuck\" feelings",
  "Existential concerns / loss of meaning",
  "Life review and meaning-making",
  "Personal growth and self-development goals",
  "Friendship difficulties / social isolation",
  "Social isolation",
  "Loneliness and social isolation",

  // Grief & Loss
  "Grief & Loss",
  "Bereavement",
  "Grief and bereavement",
  "Loss",

  // Physical & Medical
  "Chronic Pain and illness",
  "Chronic illness or loss of independence",
  "Adjustment to health conditions",
  "Pain Management",
  "Psychosomatic symptoms",
  "Insomnia Disorder",
  "Sleep terror disorder",

  // Adjustment
  "Adjustment Disorder",
  "General Adaptation Disorder (Adjustment Disorder)",

  // Attachment
  "Attachment Disorder",

  // Psychosis & Severe Mental Health
  "Psychosis",
  "Schizophrenia",
  "Hearing Voices and Paranoia",

  // Children & Adolescents
  "Bullying / peer difficulties",
  "Emotional regulation / behavioural difficulties",
  "school refusal or perfectionism",
  "Oppositional Defiant Disorder (ODD)",
  "Social skill development needs",

  // Professional & Workplace
  "Bullying / workplace conflict",
  "Executive and Professional Coaching",
  "Professional identity and role strain",
  "Identity or career pressures",
  "Carers and support workers",
].sort();

export const CANONICAL_MODALITIES: string[] = [
  "Acceptance and Commitment Therapy (ACT)",
  "Acceptance-Based Couples Therapy",
  "Attachment-Based Therapy",
  "Behavioural Activation (BA)",
  "Circle of Security (COS)",
  "Coaching Psychology",
  "Cognitive Behavioural Therapy (CBT)",
  "Collaborative Problem Solving (CPS)",
  "Compassion-Focused Therapy (CFT)",
  "Compassionate Inquiry",
  "Couples Counselling",
  "Dialectical Behaviour Therapy (DBT)",
  "Eclectic / Integrative Therapy",
  "Emotionally Focused Therapy (EFT)",
  "Existential Therapy",
  "Exposure and Response Prevention (ERP)",
  "Eye Movement Desensitisation and Reprocessing (EMDR)",
  "Family Systems Therapy",
  "Gestalt Therapy",
  "Gottman Method Couples Therapy",
  "Humanistic / Person-Centred Therapy",
  "Intensive Short Term Dynamic Psychotherapy (ISTDP)",
  "Internal Family Systems (IFS) / Parts Work - Certified Level 1",
  "Internal Family Systems (IFS) / Parts Work - Informed",
  "Interpersonal Therapy (IPT)",
  "LGBTQIA+ Informed Therapies",
  "Mindfulness",
  "Mindfulness-Based Cognitive Therapy (MBCT)",
  "Motivational Interviewing (MI)",
  "Narrative Exposure Therapy (NET)",
  "Narrative Therapy",
  "Play Therapy",
  "Polyvagal-Informed Therapy",
  "Positive Psychology Coaching",
  "Psychedelic-Assisted Psychotherapy (research/emerging)",
  "Psychoanalytic Psychotherapy",
  "Psychodynamic Psychotherapy",
  "Psychoeducation and Skills Training",
  "Relational Life Therapy",
  "Schema Therapy",
  "Sensorimotor Psychotherapy",
  "Sex Therapy",
  "Solution-Focused Brief Therapy (SFBT)",
  "Somatic Experiencing",
  "Somatic Psychotherapy",
  "Supportive Therapy",
  "Transpersonal Psychology",
  "Trauma-Focused Cognitive Behavioural Therapy (TF-CBT)",
  "Trauma-Informed Care",
].sort();
