export type Location = {
  location: string;
  availability: string | string[];
  weekly_availability?: any[];
  fortnightly_availability?: any[];
};

export type Practitioner = {
  id?: number;
  name: string;
  title: string;
  fees: string;
  medicare_rebate: string;
  gender: string;
  alert: string;
  presentations: string | string[];
  modalities: string | string[];
  client_types: string;
  age_range: string;
  therapist_type: string;
  pronouns: string;
  billing_types?: string;
  languages?: string;
  pap_clinician?: string;
  after_hours?: string;
  religions_groups?: string;
  link_to_bio?: string;
  bio: string;
  qualifications: string;
  last_updated: string;
  locations: Location[];
  accepts_couples?: boolean;
  short_bio?: string;
  working_hours?: string;
  location_notes?: Record<string, string>;
  photo_url?: string;
  style?: string;
  availability?: string[] | Array<{ location: string; weekly: string[]; fortnightly: string[]; monthly?: string[] }>;
  additional_info?: string;
  spare_time?: string;
  telehealth?: boolean | string;
  weekly_availability?: any[];
  fortnightly_availability?: any[];
  photo_b64?: string;
  acceptingNewClients?: boolean | string;
  referral_only?: boolean;
  referral_clinic?: string;
  referral_address?: string;
  referral_phone?: string;
  referral_contact?: string;
  referral_website?: string;
  bio_url?: string;
  alert_type?: string;
  [key: string]: any;
};
